name: Continuous Integration

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ["9.0", "9.2", "9.4", "9.6"]
    env:
      STACK_YAML: stack-${{ matrix.ghc }}.yaml
    runs-on: ${{ matrix.os }}
    steps:
      # 1. checkout
      - uses: actions/checkout@v4

      # cache ~/.stack and .stack work, using matrix dimensions as keys
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ matrix.ghc }}-${{ hashFiles(env.STACK_YAML) }}

      # run stack test
      - name: Run stack test
        run: stack test --keep-going
